"use client";

import { useState, useEffect } from "react";
import Image from "next/image";
import { Label } from "@/components/ui/label";
import { Slider } from "@/components/ui/slider";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch"; 
import { Input } from "@/components/ui/input"; 
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog"; 
import { calculateSizing, ClusterInputs, SizingResults } from "@/lib/calculator";
import { Server, Cpu, Save, Layers, Mail, Info, DollarSign, Check, HardDrive, Share2, TrendingUp, Users, Lock } from "lucide-react";

export default function Tool() {
  // HYDRATION FIX: Prevents server/client mismatch errors
  const [mounted, setMounted] = useState(false);

  const [inputs, setInputs] = useState<ClusterInputs>({
    // Inventory
    sourceHosts: 10,
    sourceSockets: 2,
    sourceCoresPerSocket: 16,
    sourceRam: 384,
    sourceUsableStorage: 100,
    
    // New Logic
    growthFactor: 10, 
    storageEfficiency: true, 
    includeMigrationServices: false,

    // Target
    targetCpuType: "amd",
    targetCoresPerSocket: 64, 
    targetRam: 768,
    targetRawStorage: 80,
    applyModernization: true,
    applyCvmOverhead: true,
    redundancyLevel: "n+1",
    targetLicense: "pro",
    showFinancials: false,
  });

  const [results, setResults] = useState<SizingResults | null>(null);
  
  // LEAD GEN STATES
  const [isLeadModalOpen, setIsLeadModalOpen] = useState(false);
  const [email, setEmail] = useState("");
  const [isEmailSubmitted, setIsEmailSubmitted] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => {
    setMounted(true);
    setResults(calculateSizing(inputs));
  }, [inputs]);

  const handlePdfClick = () => {
    if (isEmailSubmitted) {
      window.print();
    } else {
      setIsLeadModalOpen(true);
    }
  };

  // HANDLE FORM SUBMIT
  const handleLeadSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!email || !email.includes("@")) return;

    setIsSubmitting(true);

    const formData = new URLSearchParams();
    formData.append("email", email);
    formData.append("date", new Date().toISOString());
    formData.append("sourceHosts", inputs.sourceHosts.toString());
    formData.append("recommendedNodes", results?.nodesRequired.toString() || "0");
    formData.append("estSavings", results?.financials.savings.toString() || "0");
    formData.append("migrationServices", inputs.includeMigrationServices ? "Yes" : "No");

    try {
      await fetch("https://hooks.zapier.com/hooks/catch/25831933/uajd22h/", { 
        method: "POST",
        mode: "no-cors",
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        body: formData.toString()
      });
      
      console.log("Lead sent to Zapier!");
    } catch (err) {
      console.error("Failed to send lead", err);
    }

    setIsSubmitting(false);
    setIsEmailSubmitted(true);
    setIsLeadModalOpen(false);
    
    setTimeout(() => window.print(), 500);
  };

  const handleEmail = () => {
    if (!results) return;
    const subject = `VMware Renewal Estimate: ${inputs.sourceHosts} Hosts (Migration Sizing)`;
    // UPDATED: Header changed to match branding
    const body = `*** VMWARE RENEWAL ESTIMATE & TCO REPORT ***\n\n--- CURRENT STATE ---\n• Hosts: ${inputs.sourceHosts}\n• Total Cores: ${results.sourceTotalCores}\n\n--- TARGET STATE ---\n• Recommended Nodes: ${results.nodesRequired}\n• HW: ${inputs.targetCpuType.toUpperCase()} Gen 5, ${inputs.targetCoresPerSocket} Cores\n\n--- FINANCIALS ---\n• Est. Savings: $${results.financials.savings.toLocaleString()} (${results.financials.savingsPct}%)\n• Nutanix TCO: $${results.financials.totalNutanixTco.toLocaleString()}\n  - Includes HW, SW, and ${inputs.includeMigrationServices ? 'Migration Services' : 'No Services'}\n\nGenerated by Rack2Cloud`;
    window.open(`mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`);
  };

  const applyPreset = (type: 'entry' | 'balanced' | 'performance') => {
    if (type === 'entry') setInputs(p => ({ ...p, targetCoresPerSocket: 24, targetRam: 384, targetRawStorage: 40 }));
    if (type === 'balanced') setInputs(p => ({ ...p, targetCoresPerSocket: 48, targetRam: 768, targetRawStorage: 80 }));
    if (type === 'performance') setInputs(p => ({ ...p, targetCoresPerSocket: 96, targetRam: 1536, targetRawStorage: 150 }));
  };

  // Prevent rendering until client-side hydration is complete
  if (!mounted) return null;

  return (
    <div className="min-h-screen bg-[#0b0e14] text-slate-100 font-sans p-4 md:p-8 flex justify-center print:bg-white print:text-black print:p-0">
      <div className="w-full max-w-6xl space-y-6 print:space-y-4 print:max-w-none">
        
        {/* HEADER */}
        <div className="bg-[#11161f] rounded-xl border border-slate-800/60 p-6 flex flex-col md:flex-row justify-between items-center gap-6 shadow-2xl print:shadow-none print:border-b-2 print:border-slate-300 print:rounded-none print:bg-white print:p-0 print:mb-8">
           <div className="flex items-center gap-4">
              <Image src="https://www.rack2cloud.com/wp-content/uploads/2025/12/Icon.png" alt="Rack2Cloud" width={48} height={48} className="object-contain" />
              <div>
                <h1 className="text-2xl font-black text-white uppercase tracking-wide print:text-black">Rack2Cloud</h1>
                <p className="text-slate-400 text-xs font-bold uppercase tracking-[0.2em] print:text-slate-600">VMware Renewal Estimator</p>
              </div>
           </div>
           <div className="flex gap-3 print:hidden">
             <Button onClick={handleEmail} variant="outline" className="border-slate-700 bg-transparent text-slate-300 hover:text-white hover:bg-slate-800 h-10 px-6 rounded-xl text-xs font-bold uppercase tracking-wide transition-all">
               <Share2 className="w-4 h-4 mr-2" /> Share
             </Button>
             <Button onClick={handlePdfClick} className="bg-blue-600 hover:bg-blue-500 text-white rounded-xl font-bold uppercase text-xs h-10 px-6 shadow-[0_0_15px_rgba(37,99,235,0.4)] transition-all">
               <Save className="w-4 h-4 mr-2" /> PDF Report
             </Button>
           </div>
        </div>

        {/* LEAD GEN MODAL */}
        <Dialog open={isLeadModalOpen} onOpenChange={setIsLeadModalOpen}>
          <DialogContent className="bg-[#11161f] border-slate-800 text-slate-100 sm:max-w-md print:hidden">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2 text-xl font-black uppercase tracking-wide">
                <Lock className="w-5 h-5 text-blue-500" /> Unlock Full Report
              </DialogTitle>
              {/* UPDATED: Text matches new branding */}
              <DialogDescription className="text-slate-400">
                Enter your email to instantly generate and download your detailed VMware Renewal Estimate Report.
              </DialogDescription>
            </DialogHeader>
            <form onSubmit={handleLeadSubmit} className="space-y-4 py-4">
              <div className="space-y-2">
                <Label className="text-xs font-bold uppercase text-slate-500">Business Email</Label>
                <Input type="email" placeholder="name@company.com" required value={email} onChange={(e) => setEmail(e.target.value)} className="bg-[#0b0e14] border-slate-700 text-white focus:border-blue-500" />
              </div>
              <DialogFooter>
                <Button type="submit" disabled={isSubmitting} className="w-full bg-blue-600 hover:bg-blue-500 font-bold uppercase tracking-wide">
                  {isSubmitting ? "Generating..." : "Download Report"}
                </Button>
              </DialogFooter>
            </form>
            <div className="text-[10px] text-slate-500 text-center px-4 leading-tight">
              We respect your inbox. Providing your email unlocks the report tool. <span className="text-slate-400 font-bold block mt-1">We will not call you unless explicitly requested.</span>
            </div>
          </DialogContent>
        </Dialog>

        <div className="grid lg:grid-cols-12 gap-6 print:block">
          
          {/* LEFT COL: INPUTS */}
          <div className="lg:col-span-7 space-y-6 print:mb-8">
            {/* CURRENT INVENTORY */}
            <div className="bg-[#11161f] rounded-xl border border-slate-800/60 p-6 print:bg-white print:border print:border-slate-300">
              <h3 className="text-slate-400 text-xs font-bold uppercase tracking-wider mb-6 flex items-center gap-2 print:text-black">
                <Server className="w-4 h-4" /> Current Inventory (Demand)
              </h3>
              <div className="grid md:grid-cols-2 gap-x-6 gap-y-6 mb-8">
                
                {/* Source Hosts */}
                <div>
                    <div className="flex justify-between mb-2 items-center">
                        <Label className="text-xs font-bold text-slate-500 uppercase print:text-slate-700">Legacy Hosts</Label>
                        <Input 
                            type="number" 
                            className="w-16 h-6 text-right font-mono font-bold bg-[#0b0e14] border-slate-700 text-white text-xs p-1 print:text-black print:bg-white print:border-slate-300"
                            value={inputs.sourceHosts}
                            onChange={(e) => setInputs({...inputs, sourceHosts: Number(e.target.value)})}
                        />
                    </div>
                    <Slider value={[inputs.sourceHosts]} min={1} max={50} onValueChange={(v) => setInputs({...inputs, sourceHosts: v[0]})} className="[&>.relative>.absolute]:bg-slate-500 print:hidden" />
                </div>

                {/* Cores Per CPU */}
                <div>
                    <div className="flex justify-between mb-2 items-center">
                        <Label className="text-xs font-bold text-slate-500 uppercase print:text-slate-700">Cores / CPU</Label>
                        <Input 
                            type="number" 
                            className="w-16 h-6 text-right font-mono font-bold bg-[#0b0e14] border-slate-700 text-white text-xs p-1 print:text-black print:bg-white print:border-slate-300"
                            value={inputs.sourceCoresPerSocket}
                            onChange={(e) => setInputs({...inputs, sourceCoresPerSocket: Number(e.target.value)})}
                        />
                    </div>
                    <Slider value={[inputs.sourceCoresPerSocket]} min={8} max={32} step={2} onValueChange={(v) => setInputs({...inputs, sourceCoresPerSocket: v[0]})} className="[&>.relative>.absolute]:bg-slate-500 print:hidden" />
                </div>

                {/* RAM */}
                <div>
                    <div className="flex justify-between mb-2 items-center">
                        <Label className="text-xs font-bold text-slate-500 uppercase print:text-slate-700">RAM (GB)</Label>
                        <Input 
                            type="number" 
                            className="w-16 h-6 text-right font-mono font-bold bg-[#0b0e14] border-slate-700 text-white text-xs p-1 print:text-black print:bg-white print:border-slate-300"
                            value={inputs.sourceRam}
                            onChange={(e) => setInputs({...inputs, sourceRam: Number(e.target.value)})}
                        />
                    </div>
                    <Slider value={[inputs.sourceRam]} min={128} max={1024} step={32} onValueChange={(v) => setInputs({...inputs, sourceRam: v[0]})} className="[&>.relative>.absolute]:bg-slate-500 print:hidden" />
                </div>

                {/* Usable Storage */}
                <div>
                    <div className="flex justify-between mb-2 items-center">
                        <Label className="text-xs font-bold text-slate-500 uppercase print:text-slate-700">Usable Storage (TB)</Label>
                        <Input 
                            type="number" 
                            className="w-16 h-6 text-right font-mono font-bold bg-[#0b0e14] border-slate-700 text-white text-xs p-1 print:text-black print:bg-white print:border-slate-300"
                            value={inputs.sourceUsableStorage}
                            onChange={(e) => setInputs({...inputs, sourceUsableStorage: Number(e.target.value)})}
                        />
                    </div>
                    <Slider value={[inputs.sourceUsableStorage]} min={10} max={500} step={10} onValueChange={(v) => setInputs({...inputs, sourceUsableStorage: v[0]})} className="[&>.relative>.absolute]:bg-slate-500 print:hidden" />
                </div>
              </div>

              {/* Growth Buffer */}
              <div className="mb-8 flex items-center gap-4 bg-[#0b0e14] px-4 py-3 rounded-lg border border-slate-800/80 print:bg-white print:border-slate-200">
                   <div className="flex items-center gap-2 shrink-0">
                        <TrendingUp className="w-4 h-4 text-emerald-500 print:text-emerald-700" />
                        <span className="text-xs text-slate-300 font-bold uppercase print:text-slate-700">Growth Buffer</span>
                   </div>
                   <Slider value={[inputs.growthFactor]} min={0} max={50} step={5} onValueChange={(v) => setInputs({...inputs, growthFactor: v[0]})} className="grow [&>.relative>.absolute]:bg-emerald-500 print:hidden" />
                   <span className="text-sm text-emerald-400 font-mono font-bold shrink-0 w-12 text-right print:text-emerald-700">+{inputs.growthFactor}%</span>
              </div>

              <div className="bg-[#0b0e14] rounded-lg p-3 grid grid-cols-3 gap-2 border border-slate-800/50 print:bg-slate-100 print:border-slate-300">
                <div className="text-center">
                    <div className="text-[10px] text-slate-500 uppercase font-bold print:text-slate-600">Total Cores</div>
                    <div className="text-slate-200 font-mono font-bold print:text-black">{results?.sourceTotalCores}</div>
                </div>
                <div className="text-center border-l border-slate-800 print:border-slate-300">
                    <div className="text-[10px] text-slate-500 uppercase font-bold print:text-slate-600">Total RAM</div>
                    <div className="text-slate-200 font-mono font-bold print:text-black">{(results?.sourceTotalRam || 0) / 1024 > 1 ? `${((results?.sourceTotalRam || 0)/1024).toFixed(1)} TB` : `${results?.sourceTotalRam} GB`}</div>
                </div>
                <div className="text-center border-l border-slate-800 print:border-slate-300">
                    <div className="text-[10px] text-slate-500 uppercase font-bold print:text-slate-600">Total Storage</div>
                    <div className="text-slate-200 font-mono font-bold print:text-black">{results?.sourceTotalStorage} TB</div>
                </div>
              </div>
            </div>

            {/* TARGET HARDWARE */}
            <div className="bg-[#11161f] rounded-xl border border-slate-800/60 p-6 relative overflow-hidden print:bg-white print:border print:border-slate-300">
              <div className="absolute top-0 left-0 w-1 h-full bg-blue-600"></div>
              <div className="flex justify-between items-center mb-6">
                <h3 className="text-blue-500 text-xs font-bold uppercase tracking-wider flex items-center gap-2 print:text-blue-700">
                    <Cpu className="w-4 h-4" /> Target Hardware (Supply)
                </h3>
                <div className="flex gap-1 bg-[#0b0e14] p-1 rounded border border-slate-800 print:hidden">
                  <button onClick={() => applyPreset('entry')} className="px-3 py-1 text-[10px] uppercase font-bold text-slate-400 hover:text-white hover:bg-slate-800 rounded transition-colors">Entry</button>
                  <button onClick={() => applyPreset('balanced')} className="px-3 py-1 text-[10px] uppercase font-bold text-slate-400 hover:text-white hover:bg-slate-800 rounded transition-colors">Balanced</button>
                  <button onClick={() => applyPreset('performance')} className="px-3 py-1 text-[10px] uppercase font-bold text-slate-400 hover:text-white hover:bg-slate-800 rounded transition-colors">Perf</button>
                </div>
              </div>
              <div className="grid md:grid-cols-2 gap-x-6 gap-y-6">
                <div className="space-y-2">
                    <Label className="text-xs font-bold text-blue-400 uppercase print:text-blue-700">Target CPU Generation</Label>
                    <select className="w-full bg-[#0b0e14] border border-slate-700 text-white text-sm rounded-md p-2.5 focus:border-blue-500 outline-none print:bg-white print:text-black print:border-slate-300" value={inputs.targetCpuType} onChange={(e) => setInputs({...inputs, targetCpuType: e.target.value as "intel" | "amd"})}><option value="intel">Intel Xeon (Gen 5 Emerald Rapids)</option><option value="amd">AMD EPYC (Gen 5 Turin)</option></select>
                </div>
                <div className="space-y-2">
                    <Label className="text-xs font-bold text-blue-400 uppercase print:text-blue-700">CVM Overhead Logic</Label>
                    <select className="w-full bg-[#0b0e14] border border-slate-700 text-white text-sm rounded-md p-2.5 focus:border-blue-500 outline-none print:bg-white print:text-black print:border-slate-300" value={inputs.applyCvmOverhead ? "yes" : "no"} onChange={(e) => setInputs({...inputs, applyCvmOverhead: e.target.value === "yes"})}><option value="yes">Factor Nutanix CVM (Recommended)</option><option value="no">Ignore Overhead (Raw Capacity)</option></select>
                </div>
                
                <div className="md:col-span-2">
                    <div className="flex justify-between mb-2 items-center">
                        <Label className="text-xs font-bold text-slate-500 uppercase print:text-slate-700">Target Cores/Socket</Label>
                        <span className="font-mono font-bold text-blue-400 print:text-blue-700">{inputs.targetCoresPerSocket}</span>
                    </div>
                    <Slider value={[inputs.targetCoresPerSocket]} min={16} max={128} step={8} onValueChange={(v) => setInputs({...inputs, targetCoresPerSocket: v[0]})} className="[&>.relative>.absolute]:bg-blue-600 print:hidden" />
                </div>
                
                <div>
                    <div className="flex justify-between mb-2 items-center">
                        <Label className="text-xs font-bold text-slate-500 uppercase print:text-slate-700">RAM/Node (GB)</Label>
                        <span className="font-mono font-bold text-blue-400 print:text-blue-700">{inputs.targetRam}</span>
                    </div>
                    <Slider value={[inputs.targetRam]} min={256} max={3072} step={64} onValueChange={(v) => setInputs({...inputs, targetRam: v[0]})} className="[&>.relative>.absolute]:bg-blue-600 print:hidden" />
                </div>
                
                <div>
                    <div className="flex justify-between mb-2 items-center">
                        <Label className="text-xs font-bold text-slate-500 uppercase print:text-slate-700">Raw Storage/Node (TB)</Label>
                        <span className="font-mono font-bold text-blue-400 print:text-blue-700">{inputs.targetRawStorage}</span>
                    </div>
                    <Slider value={[inputs.targetRawStorage]} min={20} max={300} step={10} onValueChange={(v) => setInputs({...inputs, targetRawStorage: v[0]})} className="[&>.relative>.absolute]:bg-blue-600 print:hidden" />
                </div>
              </div>

              <div className="mt-8 bg-blue-950/20 border border-blue-900/40 rounded-lg p-4 grid md:grid-cols-3 gap-4 print:bg-slate-50 print:border-slate-200">
                <div className="flex flex-col gap-2">
                    <div className="flex justify-between items-center">
                        <Label className="text-xs uppercase font-bold text-blue-400 print:text-blue-700">Modern CPU Factor</Label>
                        <Switch checked={inputs.applyModernization} onCheckedChange={(c) => setInputs({...inputs, applyModernization: c})} className="print:hidden" />
                        <span className="hidden print:inline text-xs font-bold">{inputs.applyModernization ? "Yes" : "No"}</span>
                    </div>
                    <span className="text-[10px] text-slate-400 print:text-slate-500">Gen 5 provides 1.25x-1.4x density</span>
                </div>
                <div className="flex flex-col gap-2 border-l border-blue-900/30 pl-4 print:border-slate-300">
                    <div className="flex justify-between items-center">
                        <Label className="text-xs uppercase font-bold text-blue-400 print:text-blue-700">Data Reduction</Label>
                        <Switch checked={inputs.storageEfficiency} onCheckedChange={(c) => setInputs({...inputs, storageEfficiency: c})} className="print:hidden" />
                        <span className="hidden print:inline text-xs font-bold">{inputs.storageEfficiency ? "Yes" : "No"}</span>
                    </div>
                    <span className="text-[10px] text-slate-400 print:text-slate-500">Apply 1.5:1 Compression Ratio</span>
                </div>
                <div className="flex flex-col gap-2 border-l border-blue-900/30 pl-4 print:border-slate-300">
                    <Label className="text-xs uppercase font-bold text-blue-400 print:text-blue-700">Cluster HA</Label>
                    <select className="bg-[#0b0e14] border border-slate-700 text-white text-xs rounded px-2 py-1 focus:border-blue-500 outline-none uppercase font-bold print:bg-white print:text-black print:border-slate-300" value={inputs.redundancyLevel} onChange={(e) => setInputs({...inputs, redundancyLevel: e.target.value as any})}><option value="none">None</option><option value="n+1">N+1</option><option value="n+2">N+2</option></select>
                </div>
              </div>

              <div className="mt-6 bg-[#0b0e14] rounded-lg p-3 grid grid-cols-3 gap-2 border border-blue-900/30 print:bg-slate-100 print:border-slate-300">
                <div className="text-center">
                    <div className="text-[10px] text-blue-500 uppercase font-bold print:text-blue-700">New Cores</div>
                    <div className="text-blue-200 font-mono font-bold print:text-black">{results?.targetTotalCores}</div>
                </div>
                <div className="text-center border-l border-slate-800 print:border-slate-300">
                    <div className="text-[10px] text-blue-500 uppercase font-bold print:text-blue-700">New RAM</div>
                    <div className="text-blue-200 font-mono font-bold print:text-black">{(results?.targetTotalRam || 0) / 1024 > 1 ? `${((results?.targetTotalRam || 0)/1024).toFixed(1)} TB` : `${results?.targetTotalRam} GB`}</div>
                </div>
                <div className="text-center border-l border-slate-800 print:border-slate-300">
                    <div className="text-[10px] text-blue-500 uppercase font-bold print:text-blue-700">Usable Storage</div>
                    <div className="text-blue-200 font-mono font-bold print:text-black">{results?.targetTotalStorage.toFixed(0)} TB</div>
                </div>
              </div>
            </div>
          </div>

          {/* RIGHT COL */}
          <div className="lg:col-span-5 space-y-6">
            
            {/* RESULTS CARD */}
            <div className="bg-[#161b26] rounded-xl border border-blue-900/30 p-8 flex flex-col items-center justify-center text-center relative overflow-hidden shadow-2xl print:bg-white print:border-2 print:border-black print:shadow-none">
              <div className="absolute top-0 w-full h-1 bg-gradient-to-r from-blue-600 to-cyan-400 print:hidden"></div>
              <h4 className="text-slate-400 text-xs font-bold uppercase tracking-widest mb-4 print:text-black">Recommended Configuration</h4>
              <div className="flex items-baseline gap-2 mb-2">
                <span className="text-7xl font-black text-white tracking-tighter print:text-black">{results?.nodesRequired}</span>
                <span className="text-xl font-bold text-blue-500 print:text-blue-700">Nodes</span>
              </div>
              <p className="text-slate-400 text-sm mb-6 print:text-slate-600">Replacing <strong className="text-white print:text-black">{inputs.sourceHosts} Legacy Hosts</strong></p>
              <div className="grid grid-cols-2 gap-4 w-full">
                 <div className="bg-[#0b0e14] p-4 rounded-lg border border-slate-800/60 print:bg-slate-100 print:border-slate-300">
                    <div className="text-[10px] text-blue-400 uppercase font-bold mb-1 print:text-blue-700">Consolidation</div>
                    <div className="text-2xl font-black text-white print:text-black">{results?.consolidationRatio}</div>
                 </div>
                 <div className="bg-[#0b0e14] p-4 rounded-lg border border-slate-800/60 print:bg-slate-100 print:border-slate-300">
                    <div className="text-[10px] text-amber-500 uppercase font-bold mb-1 print:text-amber-700">Limiting Factor</div>
                    <div className="text-2xl font-black text-white print:text-black">{results?.limitingFactor}</div>
                 </div>
              </div>
            </div>

            {/* LICENSING */}
            <div className="bg-[#11161f] rounded-xl border border-slate-800/60 p-6 print:bg-white print:border print:border-slate-300">
               <h4 className="text-slate-400 text-xs font-bold uppercase tracking-widest mb-6 flex items-center gap-2 print:text-black">
                <Layers className="w-4 h-4" /> Licensing Mapping
               </h4>
               <div className="mb-6">
                <Label className="text-[10px] font-bold text-slate-500 uppercase mb-1 block print:text-slate-700">Nutanix NCI Edition</Label>
                <select className="w-full bg-[#0b0e14] border border-slate-700 text-white text-sm rounded-md p-2.5 focus:border-blue-500 outline-none print:bg-white print:text-black print:border-slate-300" value={inputs.targetLicense} onChange={(e) => setInputs({...inputs, targetLicense: e.target.value as any})}><option value="starter">NCI Starter (Basic)</option><option value="pro">NCI Pro (Standard)</option><option value="ultimate">NCI Ultimate (Full Stack)</option></select>
               </div>
               <div className="grid grid-cols-2 gap-4">
                 <div className="bg-blue-950/20 border border-blue-900/40 rounded-lg p-3 relative print:bg-blue-50 print:border-blue-200">
                    <div className="text-[10px] text-blue-400 font-bold uppercase mb-1 print:text-blue-700">Proposed</div>
                    <div className="text-lg font-bold text-white mb-1 print:text-black">{results?.nutanixEdition}</div>
                    <div className="text-[10px] text-slate-400 leading-tight print:text-slate-600">{inputs.targetLicense === 'starter' && "Core HCI features only."}{inputs.targetLicense === 'pro' && "Includes AHV, Files, Data Protection."}{inputs.targetLicense === 'ultimate' && "Full Multisite DR + Security + Advanced Automation."}</div>
                 </div>
                 <div className="bg-[#0b0e14] border border-slate-800 rounded-lg p-3 opacity-70 print:bg-slate-100 print:border-slate-300">
                    <div className="text-[10px] text-slate-500 font-bold uppercase mb-1 print:text-slate-700">VMware Equivalent</div>
                    <div className="text-lg font-bold text-slate-300 mb-1 print:text-black">{results?.vmwareEdition}</div>
                    <div className="text-[10px] text-slate-500 leading-tight print:text-slate-600">Comparable VCF/VVF Bundle based on features.</div>
                 </div>
               </div>
            </div>

            {/* FINANCIALS TOGGLE */}
            <div onClick={() => setInputs(p => ({ ...p, showFinancials: !p.showFinancials }))} className="group flex items-center justify-between bg-[#11161f] p-4 rounded-xl border border-slate-800/60 cursor-pointer hover:border-emerald-900/50 transition-colors print:hidden">
              <div className="flex items-center gap-2">
                  <div className="bg-emerald-900/30 p-1.5 rounded text-emerald-500"><DollarSign className="w-4 h-4"/></div>
                  <Label className="text-xs font-bold text-slate-300 uppercase cursor-pointer group-hover:text-emerald-400 transition-colors">Show Financial Estimates</Label>
              </div>
              <Switch checked={inputs.showFinancials} />
            </div>

            {/* FINANCIALS PANEL */}
            {(inputs.showFinancials || inputs.showFinancials === undefined /* force show on print if needed via css logic later, but for now relies on state */) && (
               <div className={`bg-emerald-950/20 rounded-xl border border-emerald-900/40 p-6 relative overflow-hidden animate-in slide-in-from-top-4 fade-in duration-300 print:bg-white print:border-emerald-600 print:border-2 ${!inputs.showFinancials ? 'print:hidden' : ''}`}>
                  <div className="absolute top-0 left-0 w-1 h-full bg-emerald-500"></div>
                  <h4 className="text-emerald-500 text-xs font-bold uppercase tracking-widest mb-4 print:text-emerald-700">3-Year TCO Savings</h4>
                  <div className="flex items-baseline gap-1 mb-2">
                    <span className="text-4xl font-black text-white tracking-tighter print:text-black">${(results?.financials.savings || 0).toLocaleString()}</span>
                  </div>
                  <p className="text-emerald-400/60 text-xs font-bold mb-6 print:text-emerald-700">{results?.financials.savingsPct}% Cost Reduction</p>
                  
                  <div className="mb-4 flex items-center justify-between bg-emerald-900/20 p-2.5 rounded-lg border border-emerald-900/30 print:bg-emerald-50 print:border-emerald-200">
                      <div className="flex items-center gap-2">
                        <Users className="w-4 h-4 text-emerald-400 print:text-emerald-700"/>
                        <span className="text-[10px] text-emerald-100 uppercase font-bold tracking-wide print:text-emerald-900">Include Migration Services?</span>
                      </div>
                      <Switch 
                        checked={inputs.includeMigrationServices} 
                        onCheckedChange={(c) => setInputs({...inputs, includeMigrationServices: c})} 
                        className="scale-75 data-[state=unchecked]:bg-slate-950 data-[state=checked]:bg-emerald-400 border border-emerald-500/50 print:hidden" 
                      />
                      <span className="hidden print:inline text-xs font-bold print:text-emerald-900">{inputs.includeMigrationServices ? "Yes" : "No"}</span>
                  </div>

                  <div className="space-y-3 text-sm">
                      <div className="flex justify-between border-b border-emerald-900/30 pb-2 print:border-emerald-200">
                        <span className="text-slate-400 print:text-slate-600">VMware Renewal (SW Only)</span>
                        <span className="text-slate-300 font-mono print:text-black">${(results?.financials.vmwareCost || 0).toLocaleString()}</span>
                      </div>
                      <div className="flex justify-between pt-1">
                        <span className="text-slate-400 print:text-slate-600">Nutanix Total TCO</span>
                        <span className="text-emerald-400 font-mono font-bold print:text-emerald-700">${(results?.financials.totalNutanixTco || 0).toLocaleString()}</span>
                      </div>
                      <div className="pl-4 space-y-1 text-xs opacity-70">
                          <div className="flex justify-between"><span className="text-slate-500 flex items-center gap-1 print:text-slate-600"><Layers className="w-3 h-3"/> License (3yr Term)</span><span className="text-slate-400 font-mono print:text-black">${(results?.financials.nutanixLicenseCost || 0).toLocaleString()}</span></div>
                          <div className="flex justify-between"><span className="text-slate-500 flex items-center gap-1 print:text-slate-600"><HardDrive className="w-3 h-3"/> Hardware (One-Time)</span><span className="text-slate-400 font-mono print:text-black">${(results?.financials.nutanixHardwareCost || 0).toLocaleString()}</span></div>
                          {inputs.includeMigrationServices && (
                            <div className="flex justify-between"><span className="text-indigo-300 flex items-center gap-1 font-bold print:text-indigo-700"><Users className="w-3 h-3"/> Migration Services</span><span className="text-indigo-300 font-mono font-bold print:text-indigo-700">${(results?.financials.migrationServicesCost || 0).toLocaleString()}</span></div>
                          )}
                      </div>
                  </div>
               </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}