"use client";

import { useState, useEffect } from "react";
import Image from "next/image";
import { Label } from "@/components/ui/label";
import { Slider } from "@/components/ui/slider";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch"; 
import { Input } from "@/components/ui/input"; 
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog"; 
import { calculateSizing, ClusterInputs, SizingResults } from "@/lib/calculator";
import { Server, Cpu, Save, Layers, Mail, Info, DollarSign, Check, HardDrive, Share2, TrendingUp, Users, Lock } from "lucide-react";

export default function Tool() {
  const [inputs, setInputs] = useState<ClusterInputs>({
    // Inventory
    sourceHosts: 10,
    sourceSockets: 2,
    sourceCoresPerSocket: 16,
    sourceRam: 384,
    sourceUsableStorage: 100,
    
    // New Logic
    growthFactor: 10, 
    storageEfficiency: true, 
    includeMigrationServices: false,

    // Target
    targetCpuType: "amd",
    targetCoresPerSocket: 64, 
    targetRam: 768,
    targetRawStorage: 80,
    applyModernization: true,
    applyCvmOverhead: true,
    redundancyLevel: "n+1",
    targetLicense: "pro",
    showFinancials: false,
  });

  const [results, setResults] = useState<SizingResults | null>(null);
  
  // LEAD GEN STATES
  const [isLeadModalOpen, setIsLeadModalOpen] = useState(false);
  const [email, setEmail] = useState("");
  const [isEmailSubmitted, setIsEmailSubmitted] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => {
    setResults(calculateSizing(inputs));
  }, [inputs]);

  const handlePdfClick = () => {
    if (isEmailSubmitted) {
      window.print();
    } else {
      setIsLeadModalOpen(true);
    }
  };

  // HANDLE FORM SUBMIT
  const handleLeadSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!email || !email.includes("@")) return;

    setIsSubmitting(true);

    const formData = new URLSearchParams();
    formData.append("email", email);
    formData.append("date", new Date().toISOString());
    formData.append("sourceHosts", inputs.sourceHosts.toString());
    formData.append("recommendedNodes", results?.nodesRequired.toString() || "0");
    formData.append("estSavings", results?.financials.savings.toString() || "0");
    formData.append("migrationServices", inputs.includeMigrationServices ? "Yes" : "No");

    try {
      await fetch("https://hooks.zapier.com/hooks/catch/25831933/uajd22h/", { 
        method: "POST",
        mode: "no-cors",
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        body: formData.toString()
      });
      
      console.log("Lead sent to Zapier!");
    } catch (err) {
      console.error("Failed to send lead", err);
    }

    setIsSubmitting(false);
    setIsEmailSubmitted(true);
    setIsLeadModalOpen(false);
    
    setTimeout(() => window.print(), 500);
  };

  const handleEmail = () => {
    if (!results) return;
    const subject = `Migration Sizing: ${inputs.sourceHosts} Hosts to Nutanix`;
    const body = `*** MIGRATION SIZING & TCO REPORT ***\n\n--- CURRENT STATE ---\n• Hosts: ${inputs.sourceHosts}\n• Total Cores: ${results.sourceTotalCores}\n\n--- TARGET STATE ---\n• Recommended Nodes: ${results.nodesRequired}\n• HW: ${inputs.targetCpuType.toUpperCase()} Gen 5, ${inputs.targetCoresPerSocket} Cores\n\n--- FINANCIALS ---\n• Est. Savings: $${results.financials.savings.toLocaleString()} (${results.financials.savingsPct}%)\n• Nutanix TCO: $${results.financials.totalNutanixTco.toLocaleString()}\n  - Includes HW, SW, and ${inputs.includeMigrationServices ? 'Migration Services' : 'No Services'}\n\nGenerated by Rack2Cloud`;
    window.open(`mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`);
  };

  const applyPreset = (type: 'entry' | 'balanced' | 'performance') => {
    if (type === 'entry') setInputs(p => ({ ...p, targetCoresPerSocket: 24, targetRam: 384, targetRawStorage: 40 }));
    if (type === 'balanced') setInputs(p => ({ ...p, targetCoresPerSocket: 48, targetRam: 768, targetRawStorage: 80 }));
    if (type === 'performance') setInputs(p => ({ ...p, targetCoresPerSocket: 96, targetRam: 1536, targetRawStorage: 150 }));
  };

  return (
    <div className="min-h-screen bg-[#0b0e14] text-slate-100 font-sans p-4 md:p-8 flex justify-center">
      <div className="w-full max-w-6xl space-y-6">
        
        {/* HEADER */}
        <div className="bg-[#11161f] rounded-xl border border-slate-800/60 p-6 flex flex-col md:flex-row justify-between items-center gap-6 shadow-2xl">
           <div className="flex items-center gap-4">
              <Image src="https://www.rack2cloud.com/wp-content/uploads/2025/12/Icon.png" alt="Rack2Cloud" width={48} height={48} className="object-contain" />
              <div>
                <h1 className="text-2xl font-black text-white uppercase tracking-wide">Rack2Cloud</h1>
                <p className="text-slate-400 text-xs font-bold uppercase tracking-[0.2em]">HCI Migration Sizer</p>
              </div>
           </div>
           <div className="flex gap-3">
             <Button onClick={handleEmail} variant="outline" className="border-slate-700 bg-transparent text-slate-300 hover:text-white hover:bg-slate-800 h-10 px-6 rounded-xl text-xs font-bold uppercase tracking-wide transition-all">
               <Share2 className="w-4 h-4 mr-2" /> Share
             </Button>
             <Button onClick={handlePdfClick} className="bg-blue-600 hover:bg-blue-500 text-white rounded-xl font-bold uppercase text-xs h-10 px-6 shadow-[0_0_15px_rgba(37,99,235,0.4)] transition-all">
               <Save className="w-4 h-4 mr-2" /> PDF Report
             </Button>
           </div>
        </div>

        {/* LEAD GEN MODAL */}
        <Dialog open={isLeadModalOpen} onOpenChange={setIsLeadModalOpen}>
          <DialogContent className="bg-[#11161f] border-slate-800 text-slate-100 sm:max-w-md">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2 text-xl font-black uppercase tracking-wide">
                <Lock className="w-5 h-5 text-blue-500" /> Unlock Full Report
              </DialogTitle>
              <DialogDescription className="text-slate-400">
                Enter your email to instantly generate and download your detailed PDF Migration Report.
              </DialogDescription>
            </DialogHeader>
            <form onSubmit={handleLeadSubmit} className="space-y-4 py-4">
              <div className="space-y-2">
                <Label className="text-xs font-bold uppercase text-slate-500">Business Email</Label>
                <Input type="email" placeholder="name@company.com" required value={email} onChange={(e) => setEmail(e.target.value)} className="bg-[#0b0e14] border-slate-700 text-white focus:border-blue-500" />
              </div>
              <DialogFooter>
                <Button type="submit" disabled={isSubmitting} className="w-full bg-blue-600 hover:bg-blue-500 font-bold uppercase tracking-wide">
                  {isSubmitting ? "Generating..." : "Download Report"}
                </Button>
              </DialogFooter>
            </form>
            <div className="text-[10px] text-slate-500 text-center px-4 leading-tight">
              We respect your inbox. Providing your email unlocks the report tool. <span className="text-slate-400 font-bold block mt-1">We will not call you unless explicitly requested.</span>
            </div>
          </DialogContent>
        </Dialog>

        <div className="grid lg:grid-cols-12 gap-6">
          
          {/* LEFT COL: INPUTS */}
          <div className="lg:col-span-7 space-y-6">
            <div className="bg-[#11161f] rounded-xl border border-slate-800/60 p-6">
              <h3 className="text-slate-400 text-xs font-bold uppercase tracking-wider mb-6 flex items-center gap-2">
                <Server className="w-4 h-4" /> Current Inventory (Demand)
              </h3>
              <div className="grid md:grid-cols-2 gap-x-6 gap-y-6 mb-8">
                <div><div className="flex justify-between mb-2"><Label className="text-xs font-bold text-slate-500 uppercase">Legacy Hosts</Label><span className="font-mono font-bold">{inputs.sourceHosts}</span></div><Slider value={[inputs.sourceHosts]} min={1} max={50} onValueChange={(v) => setInputs({...inputs, sourceHosts: v[0]})} className="[&>.relative>.absolute]:bg-slate-500" /></div>
                <div><div className="flex justify-between mb-2"><Label className="text-xs font-bold text-slate-500 uppercase">Cores / CPU</Label><span className="font-mono font-bold">{inputs.sourceCoresPerSocket}</span></div><Slider value={[inputs.sourceCoresPerSocket]} min={8} max={32} step={2} onValueChange={(v) => setInputs({...inputs, sourceCoresPerSocket: v[0]})} className="[&>.relative>.absolute]:bg-slate-500" /></div>
                <div><div className="flex justify-between mb-2"><Label className="text-xs font-bold text-slate-500 uppercase">RAM (GB)</Label><span className="font-mono font-bold">{inputs.sourceRam}</span></div><Slider value={[inputs.sourceRam]} min={128} max={1024} step={32} onValueChange={(v) => setInputs({...inputs, sourceRam: v[0]})} className="[&>.relative>.absolute]:bg-slate-500" /></div>
                <div><div className="flex justify-between mb-2"><Label className="text-xs font-bold text-slate-500 uppercase">Usable Storage (TB)</Label><span className="font-mono font-bold">{inputs.sourceUsableStorage}</span></div><Slider value={[inputs.sourceUsableStorage]} min={10} max={500} step={10} onValueChange={(v) => setInputs({...inputs, sourceUsableStorage: v[0]})} className="[&>.relative>.absolute]:bg-slate-500" /></div>
              </div>
              <div className="mb-8 flex items-center gap-4 bg-[#0b0e14] px-4 py-3 rounded-lg border border-slate-800/80">
                   <div className="flex items-center gap-2 shrink-0"><TrendingUp className="w-4 h-4 text-emerald-500" /><span className="text-xs text-slate-300 font-bold uppercase">Growth Buffer</span></div>
                   <Slider value={[inputs.growthFactor]} min={0} max={50} step={5} onValueChange={(v) => setInputs({...inputs, growthFactor: v[0]})} className="grow [&>.relative>.absolute]:bg-emerald-500" />
                   <span className="text-sm text-emerald-400 font-mono font-bold shrink-0 w-12 text-right">+{inputs.growthFactor}%</span>
              </div>
              <div className="bg-[#0b0e14] rounded-lg p-3 grid grid-cols-3 gap-2 border border-slate-800/50">
                <div className="text-center"><div className="text-[10px] text-slate-500 uppercase font-bold">Total Cores</div><div className="text-slate-200 font-mono font-bold">{results?.sourceTotalCores}</div></div>
                <div className="text-center border-l border-slate-800"><div className="text-[10px] text-slate-500 uppercase font-bold">Total RAM</div><div className="text-slate-200 font-mono font-bold">{(results?.sourceTotalRam || 0) / 1024 > 1 ? `${((results?.sourceTotalRam || 0)/1024).toFixed(1)} TB` : `${results?.sourceTotalRam} GB`}</div></div>
                <div className="text-center border-l border-slate-800"><div className="text-[10px] text-slate-500 uppercase font-bold">Total Storage</div><div className="text-slate-200 font-mono font-bold">{results?.sourceTotalStorage} TB</div></div>
              </div>
            </div>

            <div className="bg-[#11161f] rounded-xl border border-slate-800/60 p-6 relative overflow-hidden">
              <div className="absolute top-0 left-0 w-1 h-full bg-blue-600"></div>
              <div className="flex justify-between items-center mb-6">
                <h3 className="text-blue-500 text-xs font-bold uppercase tracking-wider flex items-center gap-2"><Cpu className="w-4 h-4" /> Target Hardware (Supply)</h3>
                <div className="flex gap-1 bg-[#0b0e14] p-1 rounded border border-slate-800">
                  <button onClick={() => applyPreset('entry')} className="px-3 py-1 text-[10px] uppercase font-bold text-slate-400 hover:text-white hover:bg-slate-800 rounded transition-colors">Entry</button>
                  <button onClick={() => applyPreset('balanced')} className="px-3 py-1 text-[10px] uppercase font-bold text-slate-400 hover:text-white hover:bg-slate-800 rounded transition-colors">Balanced</button>
                  <button onClick={() => applyPreset('performance')} className="px-3 py-1 text-[10px] uppercase font-bold text-slate-400 hover:text-white hover:bg-slate-800 rounded transition-colors">Perf</button>
                </div>
              </div>
              <div className="grid md:grid-cols-2 gap-x-6 gap-y-6">
                <div className="space-y-2"><Label className="text-xs font-bold text-blue-400 uppercase">Target CPU Generation</Label><select className="w-full bg-[#0b0e14] border border-slate-700 text-white text-sm rounded-md p-2.5 focus:border-blue-500 outline-none" value={inputs.targetCpuType} onChange={(e) => setInputs({...inputs, targetCpuType: e.target.value as "intel" | "amd"})}><option value="intel">Intel Xeon (Gen 5 Emerald Rapids)</option><option value="amd">AMD EPYC (Gen 5 Turin)</option></select></div>
                <div className="space-y-2"><Label className="text-xs font-bold text-blue-400 uppercase">CVM Overhead Logic</Label><select className="w-full bg-[#0b0e14] border border-slate-700 text-white text-sm rounded-md p-2.5 focus:border-blue-500 outline-none" value={inputs.applyCvmOverhead ? "yes" : "no"} onChange={(e) => setInputs({...inputs, applyCvmOverhead: e.target.value === "yes"})}><option value="yes">Factor Nutanix CVM (Recommended)</option><option value="no">Ignore Overhead (Raw Capacity)</option></select></div>
                <div className="md:col-span-2"><div className="flex justify-between mb-2"><Label className="text-xs font-bold text-slate-500 uppercase">Target Cores/Socket</Label><span className="font-mono font-bold text-blue-400">{inputs.targetCoresPerSocket}</span></div><Slider value={[inputs.targetCoresPerSocket]} min={16} max={128} step={8} onValueChange={(v) => setInputs({...inputs, targetCoresPerSocket: v[0]})} className="[&>.relative>.absolute]:bg-blue-600" /></div>
                <div><div className="flex justify-between mb-2"><Label className="text-xs font-bold text-slate-500 uppercase">RAM/Node (GB)</Label><span className="font-mono font-bold text-blue-400">{inputs.targetRam}</span></div><Slider value={[inputs.targetRam]} min={256} max={3072} step={64} onValueChange={(v) => setInputs({...inputs, targetRam: v[0]})} className="[&>.relative>.absolute]:bg-blue-600" /></div>
                <div><div className="flex justify-between mb-2"><Label className="text-xs font-bold text-slate-500 uppercase">Raw Storage/Node (TB)</Label><span className="font-mono font-bold text-blue-400">{inputs.targetRawStorage}</span></div><Slider value={[inputs.targetRawStorage]} min={20} max={300} step={10} onValueChange={(v) => setInputs({...inputs, targetRawStorage: v[0]})} className="[&>.relative>.absolute]:bg-blue-600" /></div>
              </div>
              <div className="mt-8 bg-blue-950/20 border border-blue-900/40 rounded-lg p-4 grid md:grid-cols-3 gap-4">
                <div className="flex flex-col gap-2"><div className="flex justify-between items-center"><Label className="text-xs uppercase font-bold text-blue-400">Modern CPU Factor</Label><Switch checked={inputs.applyModernization} onCheckedChange={(c) => setInputs({...inputs, applyModernization: c})} /></div><span className="text-[10px] text-slate-400">Gen 5 provides 1.25x-1.4x density</span></div>
                <div className="flex flex-col gap-2 border-l border-blue-900/30 pl-4"><div className="flex justify-between items-center"><Label className="text-xs uppercase font-bold text-blue-400">Data Reduction</Label><Switch checked={inputs.storageEfficiency} onCheckedChange={(c) => setInputs({...inputs, storageEfficiency: c})} /></div><span className="text-[10px] text-slate-400">Apply 1.5:1 Compression Ratio</span></div>
                <div className="flex flex-col gap-2 border-l border-blue-900/30 pl-4"><Label className="text-xs uppercase font-bold text-blue-400">Cluster HA</Label><select className="bg-[#0b0e14] border border-slate-700 text-white text-xs rounded px-2 py-1 focus:border-blue-500 outline-none uppercase font-bold" value={inputs.redundancyLevel} onChange={(e) => setInputs({...inputs, redundancyLevel: e.target.value as any})}><option value="none">None</option><option value="n+1">N+1</option><option value="n+2">N+2</option></select></div>
              </div>
              <div className="mt-6 bg-[#0b0e14] rounded-lg p-3 grid grid-cols-3 gap-2 border border-blue-900/30">
                <div className="text-center"><div className="text-[10px] text-blue-500 uppercase font-bold">New Cores</div><div className="text-blue-200 font-mono font-bold">{results?.targetTotalCores}</div></div>
                <div className="text-center border-l border-slate-800"><div className="text-[10px] text-blue-500 uppercase font-bold">New RAM</div><div className="text-blue-200 font-mono font-bold">{(results?.targetTotalRam || 0) / 1024 > 1 ? `${((results?.targetTotalRam || 0)/1024).toFixed(1)} TB` : `${results?.targetTotalRam} GB`}</div></div>
                <div className="text-center border-l border-slate-800"><div className="text-[10px] text-blue-500 uppercase font-bold">Usable Storage</div><div className="text-blue-200 font-mono font-bold">{results?.targetTotalStorage.toFixed(0)} TB</div></div>
              </div>
            </div>
          </div>

          {/* RIGHT COL */}
          <div className="lg:col-span-5 space-y-6">
            <div className="bg-[#161b26] rounded-xl border border-blue-900/30 p-8 flex flex-col items-center justify-center text-center relative overflow-hidden shadow-2xl">
              <div className="absolute top-0 w-full h-1 bg-gradient-to-r from-blue-600 to-cyan-400"></div>
              <h4 className="text-slate-400 text-xs font-bold uppercase tracking-widest mb-4">Recommended Configuration</h4>
              <div className="flex items-baseline gap-2 mb-2"><span className="text-7xl font-black text-white tracking-tighter">{results?.nodesRequired}</span><span className="text-xl font-bold text-blue-500">Nodes</span></div>
              <p className="text-slate-400 text-sm mb-6">Replacing <strong className="text-white">{inputs.sourceHosts} Legacy Hosts</strong></p>
              <div className="grid grid-cols-2 gap-4 w-full">
                 <div className="bg-[#0b0e14] p-4 rounded-lg border border-slate-800/60"><div className="text-[10px] text-blue-400 uppercase font-bold mb-1">Consolidation</div><div className="text-2xl font-black text-white">{results?.consolidationRatio}</div></div>
                 <div className="bg-[#0b0e14] p-4 rounded-lg border border-slate-800/60"><div className="text-[10px] text-amber-500 uppercase font-bold mb-1">Limiting Factor</div><div className="text-2xl font-black text-white">{results?.limitingFactor}</div></div>
              </div>
            </div>

            <div className="bg-[#11161f] rounded-xl border border-slate-800/60 p-6">
               <h4 className="text-slate-400 text-xs font-bold uppercase tracking-widest mb-6 flex items-center gap-2"><Layers className="w-4 h-4" /> Licensing Mapping</h4>
               <div className="mb-6"><Label className="text-[10px] font-bold text-slate-500 uppercase mb-1 block">Nutanix NCI Edition</Label><select className="w-full bg-[#0b0e14] border border-slate-700 text-white text-sm rounded-md p-2.5 focus:border-blue-500 outline-none" value={inputs.targetLicense} onChange={(e) => setInputs({...inputs, targetLicense: e.target.value as any})}><option value="starter">NCI Starter (Basic)</option><option value="pro">NCI Pro (Standard)</option><option value="ultimate">NCI Ultimate (Full Stack)</option></select></div>
               <div className="grid grid-cols-2 gap-4">
                 <div className="bg-blue-950/20 border border-blue-900/40 rounded-lg p-3 relative"><div className="text-[10px] text-blue-400 font-bold uppercase mb-1">Proposed</div><div className="text-lg font-bold text-white mb-1">{results?.nutanixEdition}</div><div className="text-[10px] text-slate-400 leading-tight">{inputs.targetLicense === 'starter' && "Core HCI features only."}{inputs.targetLicense === 'pro' && "Includes AHV, Files, Data Protection."}{inputs.targetLicense === 'ultimate' && "Full Multisite DR + Security + Advanced Automation."}</div></div>
                 <div className="bg-[#0b0e14] border border-slate-800 rounded-lg p-3 opacity-70"><div className="text-[10px] text-slate-500 font-bold uppercase mb-1">VMware Equivalent</div><div className="text-lg font-bold text-slate-300 mb-1">{results?.vmwareEdition}</div><div className="text-[10px] text-slate-500 leading-tight">Comparable VCF/VVF Bundle based on features.</div></div>
               </div>
            </div>

            <div onClick={() => setInputs(p => ({ ...p, showFinancials: !p.showFinancials }))} className="group flex items-center justify-between bg-[#11161f] p-4 rounded-xl border border-slate-800/60 cursor-pointer hover:border-emerald-900/50 transition-colors">
              <div className="flex items-center gap-2"><div className="bg-emerald-900/30 p-1.5 rounded text-emerald-500"><DollarSign className="w-4 h-4"/></div><Label className="text-xs font-bold text-slate-300 uppercase cursor-pointer group-hover:text-emerald-400 transition-colors">Show Financial Estimates</Label></div>
              <Switch checked={inputs.showFinancials} />
            </div>
            {inputs.showFinancials && (
               <div className="bg-emerald-950/20 rounded-xl border border-emerald-900/40 p-6 relative overflow-hidden animate-in slide-in-from-top-4 fade-in duration-300">
                  <div className="absolute top-0 left-0 w-1 h-full bg-emerald-500"></div>
                  <h4 className="text-emerald-500 text-xs font-bold uppercase tracking-widest mb-4">3-Year TCO Savings</h4>
                  <div className="flex items-baseline gap-1 mb-2"><span className="text-4xl font-black text-white tracking-tighter">${(results?.financials.savings || 0).toLocaleString()}</span></div>
                  <p className="text-emerald-400/60 text-xs font-bold mb-6">{results?.financials.savingsPct}% Cost Reduction</p>
                  
                  {/* VISIBILITY FIXED: Green Container + Dark Switch */}
                  <div className="mb-4 flex items-center justify-between bg-emerald-900/20 p-2.5 rounded-lg border border-emerald-900/30">
                     <div className="flex items-center gap-2">
                       <Users className="w-4 h-4 text-emerald-400"/>
                       <span className="text-[10px] text-emerald-100 uppercase font-bold tracking-wide">Include Migration Services?</span>
                     </div>
                     {/* The Switch now uses slate-950 (black) for off state to contrast against the green container */}
                     <Switch 
                       checked={inputs.includeMigrationServices} 
                       onCheckedChange={(c) => setInputs({...inputs, includeMigrationServices: c})} 
                       className="scale-75 data-[state=unchecked]:bg-slate-950 data-[state=checked]:bg-emerald-400 border border-emerald-500/50" 
                     />
                  </div>

                  <div className="space-y-3 text-sm">
                     <div className="flex justify-between border-b border-emerald-900/30 pb-2"><span className="text-slate-400">VMware Renewal (SW Only)</span><span className="text-slate-300 font-mono">${(results?.financials.vmwareCost || 0).toLocaleString()}</span></div>
                     <div className="flex justify-between pt-1"><span className="text-slate-400">Nutanix Total TCO</span><span className="text-emerald-400 font-mono font-bold">${(results?.financials.totalNutanixTco || 0).toLocaleString()}</span></div>
                     <div className="pl-4 space-y-1 text-xs opacity-70">
                         <div className="flex justify-between"><span className="text-slate-500 flex items-center gap-1"><Layers className="w-3 h-3"/> License (3yr Term)</span><span className="text-slate-400 font-mono">${(results?.financials.nutanixLicenseCost || 0).toLocaleString()}</span></div>
                         <div className="flex justify-between"><span className="text-slate-500 flex items-center gap-1"><HardDrive className="w-3 h-3"/> Hardware (One-Time)</span><span className="text-slate-400 font-mono">${(results?.financials.nutanixHardwareCost || 0).toLocaleString()}</span></div>
                         {inputs.includeMigrationServices && (
                           <div className="flex justify-between"><span className="text-indigo-300 flex items-center gap-1 font-bold"><Users className="w-3 h-3"/> Migration Services</span><span className="text-indigo-300 font-mono font-bold">${(results?.financials.migrationServicesCost || 0).toLocaleString()}</span></div>
                         )}
                     </div>
                  </div>
               </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}